openapi: 3.0.0
info:
  title: Padzilla API
  description: Padzilla Open API
  version: 0.0.0
servers:
  - url: http://localhost:3000
    description: Local server for development
  - url: http://staging-api.example.com
    description: Internal staging server for testing
paths:
  /subscription/startSubscriptionSync:
    get:
      tags:
        - Subscriptions
      summary: Start subscription sync
      responses:
        200:
          description: Sync started!
        500:
          description: Interval server error!

  /subscription/stopSubscriptionSync:
    get:
      tags:
        - Subscriptions
      summary: Stop subscription sync
      responses:
        200:
          description: Sync stoped!
        500:
          description: Interval server error!

    
  /subscription/getSubscription/{zohoSubscriptionId}:
    get:
      tags:
        - Subscriptions
      summary: Get a particular subscription details
      parameters:
        - in: path
          name: zohoSubscriptionId
          schema:
            type: integer
          required: true
          description: Actual Zoho subscription id  
      responses:
        200:
          description: JWT token created!
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiry:
                    type: integer
        404:
          description: Subscription not found!
        500:
          description: Interval server error!