openapi: 3.0.0
info:
  title: Padzilla API
  description: Padzilla Open API
  version: 0.0.0
servers:
  - url: '{protocol}://{host}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        enum:
          - localhost
          - YOUR_DOMAIN_NAME
        default: 'localhost'
      port:
        enum:
          - '443'
          - '80'
          - '3000'
        default: '3000'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
paths:
  /subscription/sync/start:
    get:
      tags:
        - Subscriptions
      summary: Start subscription sync
      security:
        - bearerAuth: []  
      responses:
        200:
          description: Start subscriptions sync
        500:
          description: Interval server error

  /subscription/sync/stop:
    get:
      tags:
        - Subscriptions
      summary: Stop subscription sync
      security:
        - bearerAuth: []  
      responses:
        200:
          description: Stop subscriptions sync
        500:
          description: Interval server error

    
  /subscription/{zohoSubscriptionId}:
    get:
      tags:
        - Subscriptions
      summary: Get a particular subscription details
      security:
        - bearerAuth: []  
      parameters:
        - in: path
          name: zohoSubscriptionId
          schema:
            type: integer
          required: true
          description: Actual Zoho subscription id  
      responses:
        200:
          description: JWT token created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expiry:
                    type: integer
        404:
          description: Subscription not found
        500:
          description: Interval server error

    
  /subscription/{zohoSubscriptionId}/renew:
    get:
      tags:
        - Subscriptions
      summary: Renew a subscription
      security:
        - bearerAuth: []  
      parameters:
        - in: path
          name: zohoSubscriptionId
          schema:
            type: integer
          required: true
          description: Actual Zoho subscription id  
      responses:
        200:
          description: Get subscription details from Zoho
        404:
          description: Subscription not found
        500:
          description: Interval server error

    
  /subscription/{zohoSubscriptionId}/verify:
    get:
      tags:
        - Subscriptions
      summary: Verify a subscription
      parameters:
        - in: path
          name: zohoSubscriptionId
          schema:
            type: integer
          required: true
          description: Actual Zoho subscription id  
      responses:
        200:
          description: Get subscription details from Zoho
        404:
          description: Subscription not found
        500:
          description: Interval server error